name: openmynd
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  csv: ^6.0.0
  timezone: ^0.9.4
  sqflite: ^2.3.2
  path: ^1.8.3
  fl_chart: ^0.69.0
  flutter_iconpicker: ^3.6.1
  flutter_colorpicker: ^1.1.0
  table_calendar: ^3.1.2
  logger: ^2.4.0
  intl: ^0.19.0
  shamsi_date: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true